// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlN2jgQcaE2wpS-agApFENbbdsWLPVldc',
    appId: '1:33188801266:web:e62aa49fd191468773fe6b',
    messagingSenderId: '33188801266',
    projectId: 'yemen-store-app',
    authDomain: 'yemen-store-app.firebaseapp.com',
    storageBucket: 'yemen-store-app.firebasestorage.app',
    measurementId: 'G-NDXBEYGG06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPOwdkiMfFIRYRldqawZZCMNbTLVWcD2g',
    appId: '1:33188801266:android:1b9f1e8c8944abb673fe6b',
    messagingSenderId: '33188801266',
    projectId: 'yemen-store-app',
    storageBucket: 'yemen-store-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7jvAR0gp6TjtDI_g5mPonYNzJZpky10E',
    appId: '1:33188801266:ios:8457eaf4fac63d1a73fe6b',
    messagingSenderId: '33188801266',
    projectId: 'yemen-store-app',
    storageBucket: 'yemen-store-app.firebasestorage.app',
    iosBundleId: 'com.example.yemenStor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7jvAR0gp6TjtDI_g5mPonYNzJZpky10E',
    appId: '1:33188801266:ios:8457eaf4fac63d1a73fe6b',
    messagingSenderId: '33188801266',
    projectId: 'yemen-store-app',
    storageBucket: 'yemen-store-app.firebasestorage.app',
    iosBundleId: 'com.example.yemenStor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlN2jgQcaE2wpS-agApFENbbdsWLPVldc',
    appId: '1:33188801266:web:7bc48a9b05ca6aff73fe6b',
    messagingSenderId: '33188801266',
    projectId: 'yemen-store-app',
    authDomain: 'yemen-store-app.firebaseapp.com',
    storageBucket: 'yemen-store-app.firebasestorage.app',
    measurementId: 'G-SEG6R1M29K',
  );
}
