import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../../data/datasources/deposit_datasource.dart';
import '../../data/repositories/deposit_repository_impl.dart';
import '../../domain/entities/deposit_entity.dart';
import '../../domain/repositories/deposit_repository.dart';
import '../../domain/usecases/submit_deposit_usecase.dart';

final depositDataSourceProvider = Provider<DepositDataSource>((ref) {
  return DepositDataSourceImpl(FirebaseFirestore.instance);
});

final depositRepositoryProvider = Provider<DepositRepository>((ref) {
  final remoteDataSource = ref.watch(depositDataSourceProvider);
  return DepositRepositoryImpl(remoteDataSource);
});

final submitDepositUseCaseProvider = Provider<SubmitDepositUseCase>((ref) {
  final repository = ref.watch(depositRepositoryProvider);
  return SubmitDepositUseCase(repository);
});

// State classes for form submission
class DepositState {
  final bool isLoading;
  final String? error;
  final bool isSuccess;

  DepositState({
    this.isLoading = false,
    this.error,
    this.isSuccess = false,
  });

  DepositState copyWith({
    bool? isLoading,
    String? error,
    bool? isSuccess,
  }) {
    return DepositState(
      isLoading: isLoading ?? this.isLoading,
      error: error,
      isSuccess: isSuccess ?? this.isSuccess,
    );
  }
}

class DepositNotifier extends StateNotifier<DepositState> {
  final SubmitDepositUseCase _submitDepositUseCase;

  DepositNotifier(this._submitDepositUseCase) : super(DepositState());

  Future<void> submitDeposit({
    required double amount,
    required String currency,
    required String bankId,
    required String uniqueCode,
  }) async {
    state = state.copyWith(isLoading: true, error: null, isSuccess: false);
    
    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) {
        throw Exception("يجب تسجيل الدخول لإرسال طلب تغذية الرصيد");
      }

      // إنشاء طلب التغذية
      final deposit = DepositEntity(
        id: '', // Generated by Firestore
        userId: user.uid,
        amount: amount,
        currency: currency,
        bankId: bankId,
        uniqueCode: uniqueCode,
        createdAt: DateTime.now(),
      );

      // حفظ طلب الإيداع كـ "مقبول فوراً"
      await _submitDepositUseCase(deposit);

      // إضافة الرصيد للمستخدم فوراً
      String balanceField = 'balanceYER';
      if (currency == 'SAR') balanceField = 'balanceSAR';
      if (currency == 'USD') balanceField = 'balanceUSD';

      final userRef = FirebaseFirestore.instance.collection('users').doc(user.uid);
      await userRef.update({
        balanceField: FieldValue.increment(amount),
      });

      // إضافة إشعار داخلي بنجاح الشحن
      await FirebaseFirestore.instance.collection('notifications').add({
        'userId': user.uid,
        'title': 'تم شحن رصيدك',
        'body': 'تم بنجاح إضافة مبلغ $amount $currency إلى محفظتك.',
        'createdAt': FieldValue.serverTimestamp(),
        'isRead': false,
        'type': 'wallet_recharge'
      });

      state = state.copyWith(isLoading: false, isSuccess: true);
    } catch (e) {
      state = state.copyWith(isLoading: false, error: e.toString());
    }
  }

  void reset() {
    state = DepositState();
  }
}

final depositNotifierProvider = StateNotifierProvider<DepositNotifier, DepositState>((ref) {
  final submitDepositUseCase = ref.watch(submitDepositUseCaseProvider);
  return DepositNotifier(submitDepositUseCase);
});

final depositStatusListenerProvider = Provider<void>((ref) {
  final user = FirebaseAuth.instance.currentUser;
  if (user == null) return;

  FirebaseFirestore.instance
      .collection('deposits')
      .where('userId', isEqualTo: user.uid)
      .where('status', isEqualTo: 'accepted')
      .where('isApplied', isEqualTo: false)
      .snapshots()
      .listen((snapshot) async {
    for (var doc in snapshot.docs) {
      final data = doc.data();
      final amount = (data['amount'] as num?)?.toDouble() ?? 0.0;
      final currency = data['currency'] as String? ?? 'YER';

      String balanceField = 'balanceYER';
      if (currency == 'SAR') balanceField = 'balanceSAR';
      if (currency == 'USD') balanceField = 'balanceUSD';

      try {
        final batch = FirebaseFirestore.instance.batch();
        
        final userRef = FirebaseFirestore.instance.collection('users').doc(user.uid);
        batch.update(userRef, {
          balanceField: FieldValue.increment(amount),
        });

        batch.update(doc.reference, {
          'isApplied': true,
        });

        await batch.commit();
      } catch (e) {
        print('Error applying deposit: $e');
      }
    }
  });
});
